openapi: 3.0.2
info:
  title: OpenLineage
  version: 0.0.1
  description: OpenLineage is an open source **lineage and metadata collection API** for the data ecosystem.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /runs:
    post:
      summary: Updates the state of a run
      description: Updates a run state for a job.
      operationId: postRunStateUpdate
      tags:
        - OpenLineage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunStateUpdate'
      responses:
        '200':
          description: OK

components:
  schemas:
    Dataset:
      type: object
      properties:
        name:
          description: The unique name of the dataset
          type: string # TODO: should this be a URN?
          example: "instance.database.schema.table"
        description:
          description: The description of the Dataset.
          type: string
          example: "canonical representation of entity Foo"
        facets:
          description: The facets for this dataset
          type: object
          properties:
            schema:
              $ref: '#/components/schemas/SchemaDatasetFacet'
            dataSource:
              $ref: '#/components/schemas/DatasourceDatasetFacet'
          additionalProperties:
            $ref: '#/components/schemas/CustomFacet'
      required:
        - name

    Job:
      type: object
      properties:
        namespace:
          description: The namespace containing that job
          type: string
          example: "my-scheduler-namespace"
        name:
          description: The unique name for that job within that namespace
          type: string # TODO: should this be a URN?
          example: "myjob.mytask"
        inputs:
          description: The set of **input** datasets.
          type: array
          items:
            type: object
            properties:
              dataset:
                $ref: '#/components/schemas/Dataset'
              facets:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/CustomFacet'
        outputs:
          description: The set of **output** datasets.
          type: array
          items:
            type: object
            properties:
              dataset:
                $ref: '#/components/schemas/Dataset'
              facets:
                description: The **output** facets.
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/CustomFacet'
        description:
          description: The description of the job.
          type: string
        facets:
          description: The job facets.
          type: object
          properties:
            sourceCodeLocation:
              $ref: '#/components/schemas/SourceCodeLocationJobFacet'
          additionalProperties:
            $ref: '#/components/schemas/CustomFacet'
      required:
        - namespace
        - name

    RunStateUpdate:
      type: object
      properties:
        id:
          description: the unique identifier for that run
          type: string
          format: uuid
        transition:
          description: transitions the run state
          type: string #TODO: add enum
          example: 'START|COMPLETE|ABORT|FAIL'
        transition-time:
           type: string
           format: date-time
        job:
          $ref: '#/components/schemas/Job'
        facets:
          description: The run facets.
          type: object
          properties:
            nominalTime:
              $ref: '#/components/schemas/NominalTimeRunFacet'
          additionalProperties:
            $ref: '#/components/schemas/CustomFacet'
      required:
        - id
        - job
        - transition

    CustomFacet:
      type: object
      properties:
        origin:
          description: The name of the origin of this custom facet.
          type: string
        version:
          description: The version of this custom facet.
          type: string
      additionalProperties: true
      required:
        - origin

## Run Facets
    NominalTimeRunFacet:
      type: object
      properties:
        nominalStartTime:
          description: An [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp representing the nominal start time of the run. AKA the schedule time
          type: string
          format: date-time
        nominalEndTime:
          description: An [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) timestamp representing the nominal end time of the run.
          type: string
          format: date-time

## Job Facets
    SourceCodeLocationJobFacet:
      type: object
      properties:
        type:
          type: string
          example: git
        url:
          type: string
          format: url

## Dataset facets
    SchemaDatasetFacet:
      type: object
      properties:
        fields:
          description: The fields of the table.
          type: array
          items:
            type: object
            properties:
              name:
                description: The name of the field.
                type: string
                example: column1
              type:
                description: The type of the field.
                type: string
                example: VARCHAR|INT|...
              description:
                description: The description of the field.
                type: string
            required:
              - name
              - type

    DatasourceDatasetFacet:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
